# From https://github.com/neovim/neovim/blob/master/.stylua.toml
# call_parantheses changed for consistency
column_width = 100
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "Always"
