return {
  {
    'nvim-toggler',
    lazy = false,
    after = function(plugin)
      require('nvim-toggler').setup({
        remove_default_inverses = true,
        inverses = {
          ['true'] = 'false',
          ['True'] = 'False',
          ['yes'] = 'no',
          ['on'] = 'off',
          ['up'] = 'down',
          ['left'] = 'right',
          ['+'] = '-',
          ['('] = ')',
          ['['] = ']',
          ['{'] = '}',
          ['<'] = '>',
          ['!='] = '==',
          ['enabled'] = 'disabled',
          ['active'] = 'inactive',
          ['read'] = 'write',
          ['start'] = 'stop',
          ['open'] = 'close',
          ['first'] = 'last',
          ['get'] = 'set',
          ['large'] = 'small',
          ['parent'] = 'child',
          ['valid'] = 'invalid',
          ['push'] = 'pop',
          ['before'] = 'after',
          ['input'] = 'output',
          ['top'] = 'bottom',
          ['some'] = 'none',
          ['high'] = 'low',
          ['client'] = 'server',
          ['master'] = 'slave',
          ['compress'] = 'decompress',
          ['public'] = 'private',
          ['visible'] = 'hidden',
          ['old'] = 'new',
          ['show'] = 'hide',
        },
      })
    end,
  },
}
